version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: zzz_nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql-master
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_USER=nacos
      - MYSQL_MASTER_SERVICE_PASSWORD=123456
      - MYSQL_SLAVE_SERVICE_HOST=mysql-slave
      - MYSQL_SLAVE_SERVICE_PORT=3305
    volumes:
      - D:\data\docker\nacos\logs\:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql-slave
    restart: on-failure
  mysql-master:
    container_name: zzz_mysql_master
    image: nacos/nacos-mysql-master:latest
    env_file:
      - ./env/mysql-common.env
      - ./env/mysql-master.env
    volumes:
      - D:\data\docker\nacos\mysql-master:/var/lib/mysql
    ports:
      - "3306:3306"
  mysql-slave:
    container_name: zzz_mysql_slave
    image: nacos/nacos-mysql-slave:latest
    env_file:
      - ./env/mysql-common.env
      - ./env/mysql-slave.env
    volumes:
      - D:\data\docker\nacos\mysql-slave:/var/lib/mysql
    ports:
      - "3305:3306"
    depends_on:
      - mysql-master
  prometheus:
    container_name: zzz_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: zzz_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure

